require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 5.2.2.1

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
